apiVersion: v1
kind: Service
metadata:
  name: payroll-backend
  labels:
    app: payroll-backend
spec:
  type: LoadBalancer
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app: payroll-backend
